apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-myapp-0
  namespace: csi-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-csi
